//
//  database.swift
//  GreenQuiz
//
//  Created by Axel Remy on 19/06/2024.
//

import Foundation

var recyclages = [
    FactList(theme: "Recyclage", titre: "1", description: "Dolore aliqua aute exercitation tempor duis proident in cillum eu culpa tempor in eu ea eu. Sunt quis minim aute non ullamco sunt enim pariatur et. Adipisicing labore officia labore commodo tempor sit ad dolore et ad aute excepteur. Cupidatat enim exercitation culpa id do culpa sit in id ullamco aliqua aliqua do sit. Aliquip aliquip nulla eu occaecat adipisicing esse sunt incididunt ipsum sint nostrud exercitation elit elit."),
    FactList(theme: "Recyclage", titre: "2", description: "Dolore aliqua aute exercitation tempor duis proident in cillum eu culpa tempor in eu ea eu. Sunt quis minim aute non ullamco sunt enim pariatur et. Adipisicing labore officia labore commodo tempor sit ad dolore et ad aute excepteur. Cupidatat enim exercitation culpa id do culpa sit in id ullamco aliqua aliqua do sit. Aliquip aliquip nulla eu occaecat adipisicing esse sunt incididunt ipsum sint nostrud exercitation elit elit."),
    FactList(theme: "Recyclage", titre: "3", description: "salut aliqua aute exercitation tempor duis proident in cillum eu culpa tempor in eu ea eu. Sunt quis minim aute non ullamco sunt enim pariatur et. Adipisicing labore officia labore commodo tempor sit ad dolore et ad aute excepteur. Cupidatat enim exercitation culpa id do culpa sit in id ullamco aliqua aliqua do sit. Aliquip aliquip nulla eu occaecat adipisicing esse sunt incididunt ipsum sint nostrud exercitation elit elit."),
    FactList(theme: "Recyclage", titre: "4", description: "Dolore aliqua aute exercitation tempor duis proident in cillum eu culpa tempor in eu ea eu. Sunt quis minim aute non ullamco sunt enim pariatur et. Adipisicing labore officia labore commodo tempor sit ad dolore et ad aute excepteur. Cupidatat enim exercitation culpa id do culpa sit in id ullamco aliqua aliqua do sit. Aliquip aliquip nulla eu occaecat adipisicing esse sunt incididunt ipsum sint nostrud exercitation elit elit."),
    FactList(theme: "Recyclage", titre: "5", description: "Dolore aliqua aute exercitation tempor duis proident in cillum eu culpa tempor in eu ea eu. Sunt quis minim aute non ullamco sunt enim pariatur et. Adipisicing labore officia labore commodo tempor sit ad dolore et ad aute excepteur. Cupidatat enim exercitation culpa id do culpa sit in id ullamco aliqua aliqua do sit. Aliquip aliquip nulla eu occaecat adipisicing esse sunt incididunt ipsum sint nostrud exercitation elit elit.")
]

var impacts = [
    FactList(theme: "Impact environnemental", titre: "6", description: "bonjour ad dolore veniam aliquip aute adipisicing dolore cupidatat anim in. Cillum ad dolor elit exercitation enim officia incididunt eiusmod reprehenderit cillum. Qui ipsum laborum velit anim esse exercitation ut nulla anim ut. In magna ea eu aliquip tempor qui deserunt velit exercitation mollit commodo aute. Eiusmod cillum eu ut Lorem veniam aliquip ut cillum. Incididunt in eiusmod nulla cupidatat anim laboris mollit dolor quis dolor. Elit ut anim fugiat aliqua nostrud tempor do adipisicing."),
    FactList(theme: "Impact environnemental", titre: "7", description: "Occaecat ad dolore veniam aliquip aute adipisicing dolore cupidatat anim in. Cillum ad dolor elit exercitation enim officia incididunt eiusmod reprehenderit cillum. Qui ipsum laborum velit anim esse exercitation ut nulla anim ut. In magna ea eu aliquip tempor qui deserunt velit exercitation mollit commodo aute. Eiusmod cillum eu ut Lorem veniam aliquip ut cillum. Incididunt in eiusmod nulla cupidatat anim laboris mollit dolor quis dolor. Elit ut anim fugiat aliqua nostrud tempor do adipisicing."),
    FactList(theme: "Impact environnemental", titre: "8", description: "Occaecat ad dolore veniam aliquip aute adipisicing dolore cupidatat anim in. Cillum ad dolor elit exercitation enim officia incididunt eiusmod reprehenderit cillum. Qui ipsum laborum velit anim esse exercitation ut nulla anim ut. In magna ea eu aliquip tempor qui deserunt velit exercitation mollit commodo aute. Eiusmod cillum eu ut Lorem veniam aliquip ut cillum. Incididunt in eiusmod nulla cupidatat anim laboris mollit dolor quis dolor. Elit ut anim fugiat aliqua nostrud tempor do adipisicing."),
    FactList(theme: "Impact environnemental", titre: "9", description: "Occaecat ad dolore veniam aliquip aute adipisicing dolore cupidatat anim in. Cillum ad dolor elit exercitation enim officia incididunt eiusmod reprehenderit cillum. Qui ipsum laborum velit anim esse exercitation ut nulla anim ut. In magna ea eu aliquip tempor qui deserunt velit exercitation mollit commodo aute. Eiusmod cillum eu ut Lorem veniam aliquip ut cillum. Incididunt in eiusmod nulla cupidatat anim laboris mollit dolor quis dolor. Elit ut anim fugiat aliqua nostrud tempor do adipisicing."),
    FactList(theme: "Impact environnemental", titre: "10", description: "Occaecat ad dolore veniam aliquip aute adipisicing dolore cupidatat anim in. Cillum ad dolor elit exercitation enim officia incididunt eiusmod reprehenderit cillum. Qui ipsum laborum velit anim esse exercitation ut nulla anim ut. In magna ea eu aliquip tempor qui deserunt velit exercitation mollit commodo aute. Eiusmod cillum eu ut Lorem veniam aliquip ut cillum. Incididunt in eiusmod nulla cupidatat anim laboris mollit dolor quis dolor. Elit ut anim fugiat aliqua nostrud tempor do adipisicing."),
    FactList(theme: "Impact environnemental", titre: "11", description: "Occaecat ad dolore veniam aliquip aute adipisicing dolore cupidatat anim in. Cillum ad dolor elit exercitation enim officia incididunt eiusmod reprehenderit cillum. Qui ipsum laborum velit anim esse exercitation ut nulla anim ut. In magna ea eu aliquip tempor qui deserunt velit exercitation mollit commodo aute. Eiusmod cillum eu ut Lorem veniam aliquip ut cillum. Incididunt in eiusmod nulla cupidatat anim laboris mollit dolor quis dolor. Elit ut anim fugiat aliqua nostrud tempor do adipisicing.")
]

var waters = [
    FactList(theme: "Eau", titre: "12", description: "Mollit aute occaecat laborum et enim aliquip qui amet non nisi laboris duis. Eiusmod fugiat minim aliquip ad aliqua fugiat excepteur Lorem duis eu labore qui veniam elit. Nulla excepteur consequat consequat eiusmod laboris labore incididunt est. Sunt eiusmod nostrud fugiat eu."),
    FactList(theme: "Eau", titre: "13", description: "Mollit aute occaecat laborum et enim aliquip qui amet non nisi laboris duis. Eiusmod fugiat minim aliquip ad aliqua fugiat excepteur Lorem duis eu labore qui veniam elit. Nulla excepteur consequat consequat eiusmod laboris labore incididunt est. Sunt eiusmod nostrud fugiat eu."),
    FactList(theme: "Eau", titre: "14", description: "Mollit aute occaecat laborum et enim aliquip qui amet non nisi laboris duis. Eiusmod fugiat minim aliquip ad aliqua fugiat excepteur Lorem duis eu labore qui veniam elit. Nulla excepteur consequat consequat eiusmod laboris labore incididunt est. Sunt eiusmod nostrud fugiat eu."),
    FactList(theme: "Eau", titre: "15", description: "Mollit aute occaecat laborum et enim aliquip qui amet non nisi laboris duis. Eiusmod fugiat minim aliquip ad aliqua fugiat excepteur Lorem duis eu labore qui veniam elit. Nulla excepteur consequat consequat eiusmod laboris labore incididunt est. Sunt eiusmod nostrud fugiat eu."),
    FactList(theme: "Eau", titre: "16", description: "Mollit aute occaecat laborum et enim aliquip qui amet non nisi laboris duis. Eiusmod fugiat minim aliquip ad aliqua fugiat excepteur Lorem duis eu labore qui veniam elit. Nulla excepteur consequat consequat eiusmod laboris labore incididunt est. Sunt eiusmod nostrud fugiat eu."),
    FactList(theme: "Eau", titre: "17", description: "Mollit aute occaecat laborum et enim aliquip qui amet non nisi laboris duis. Eiusmod fugiat minim aliquip ad aliqua fugiat excepteur Lorem duis eu labore qui veniam elit. Nulla excepteur consequat consequat eiusmod laboris labore incididunt est. Sunt eiusmod nostrud fugiat eu."),

]

var homes = [
FactList(theme: "Maison", titre: "18", description: "efhdfh")
]
